In [172]:
import pandas as pd

In [173]:
df = pd.read_csv('PS_2023.03.07_18.13.34.csv', skiprows=86)
df.shape

(34030, 82)

In [174]:
df.head()

pl_name hostname  default_flag  sy_snum  sy_pnum  pl_controv_flag  \
0  11 Com b   11 Com             1        2        1                0   
1  11 Com b   11 Com             0        2        1                0   
2  11 UMi b   11 UMi             0        1        1                0   
3  11 UMi b   11 UMi             0        1        1                0   
4  11 UMi b   11 UMi             1        1        1                0   

   pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  ...  sy_disterr2  \
0  326.03000           0.32          -0.32           0.0  ...      -1.9238   
1        NaN            NaN            NaN           NaN  ...      -1.9238   
2  516.22000           3.25          -3.25           0.0  ...      -1.9765   
3        NaN            NaN            NaN           NaN  ...      -1.9765   
4  516.21997           3.20          -3.20           0.0  ...      -1.9765   

   sy_vmag  sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  \
0  4.72307        0.023       -0.023    2.282        0.346       -0.346   
1  4.72307        0.023       -0.023    2.282        0.346       -0.346   
2  5.01300        0.005       -0.005    1.939        0.270       -0.270   
3  5.01300        0.005       -0.005    1.939        0.270       -0.270   
4  5.01300        0.005       -0.005    1.939        0.270       -0.270   

   sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2  
0     4.44038        0.003848       -0.003848  
1     4.44038        0.003848       -0.003848  
2     4.56216        0.003903       -0.003903  
3     4.56216        0.003903       -0.003903  
4     4.56216        0.003903       -0.003903  

[5 rows x 82 columns]

In [175]:
print(df.isnull().sum())

pl_name             0
hostname            0
default_flag        0
sy_snum             0
sy_pnum             0
                 ... 
sy_kmagerr1       793
sy_kmagerr2       793
sy_gaiamag        856
sy_gaiamagerr1    856
sy_gaiamagerr2    856
Length: 82, dtype: int64


In [176]:
df2 = df.dropna()
df2.shape

(60, 82)

In [177]:
df3=df.iloc[:,0:50]
df3.isnull().sum()

pl_name                0
hostname               0
default_flag           0
sy_snum                0
sy_pnum                0
pl_controv_flag        0
pl_orbper           2979
pl_orbpererr1       4236
pl_orbpererr2       4237
pl_orbperlim        2979
pl_orbsmax         15360
pl_orbsmaxerr1     29343
pl_orbsmaxerr2     29344
pl_orbsmaxlim      12654
pl_rade            10566
pl_radeerr1        11217
pl_radeerr2        11217
pl_radelim          7894
pl_radj            23389
pl_radjerr1        23996
pl_radjerr2        23996
pl_radjlim         23389
pl_bmasse          28823
pl_bmasseerr1      29271
pl_bmasseerr2      29271
pl_bmasselim       28823
pl_bmassj          28824
pl_bmassjerr1      29277
pl_bmassjerr2      29277
pl_bmassjlim       28824
pl_bmassprov       28823
pl_orbeccen        17060
pl_orbeccenerr1    31176
pl_orbeccenerr2    31177
pl_orbeccenlim     14387
pl_insol           19611
pl_insolerr1       20446
pl_insolerr2       20446
pl_insollim        14672
pl_eqt             18551


In [178]:
df3=df.iloc[:,51:83]
df3.isnull().sum()

st_raderr2         7964
st_radlim          2402
st_mass            5326
st_masserr1       10645
st_masserr2       10784
st_masslim         5326
st_met            12653
st_meterr1        13307
st_meterr2        13307
st_metlim         10381
st_metratio       12842
st_logg            6093
st_loggerr1       11246
st_loggerr2       11247
st_logglim         6093
rastr                 0
ra                    0
decstr                0
dec                   0
sy_dist             802
sy_disterr1        1626
sy_disterr2        1626
sy_vmag             554
sy_vmagerr1         567
sy_vmagerr2         568
sy_kmag             573
sy_kmagerr1         793
sy_kmagerr2         793
sy_gaiamag          856
sy_gaiamagerr1      856
sy_gaiamagerr2      856
dtype: int64

In [179]:
#欠損値が15000以上の列を削除

In [180]:
df3 = df.drop(columns=['pl_orbsmaxerr1', 'pl_orbsmaxerr2', 'pl_radj', 'pl_radjerr1', 'pl_radjerr2', 'pl_radjlim', 'pl_bmasse', 'pl_bmasseerr1', 'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassj', 'pl_bmassjerr1', 'pl_bmassjerr2', 'pl_bmassjlim', 'pl_bmassprov', 'pl_orbeccen', 'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_insol', 'pl_insolerr1', 'pl_insolerr2', 'pl_eqt', 'pl_eqterr1', 'pl_eqterr2', 'st_spectype'])

In [181]:
print(df3.isnull().sum())
df3.shape

pl_name                0
hostname               0
default_flag           0
sy_snum                0
sy_pnum                0
pl_controv_flag        0
pl_orbper           2979
pl_orbpererr1       4236
pl_orbpererr2       4237
pl_orbperlim        2979
pl_orbsmax         15360
pl_orbsmaxlim      12654
pl_rade            10566
pl_radeerr1        11217
pl_radeerr2        11217
pl_radelim          7894
pl_orbeccenlim     14387
pl_insollim        14672
pl_eqtlim          15879
ttv_flag               0
st_teff             2518
st_tefferr1         3208
st_tefferr2         3449
st_tefflim          2518
st_rad              2402
st_raderr1          7825
st_raderr2          7964
st_radlim           2402
st_mass             5326
st_masserr1        10645
st_masserr2        10784
st_masslim          5326
st_met             12653
st_meterr1         13307
st_meterr2         13307
st_metlim          10381
st_metratio        12842
st_logg             6093
st_loggerr1        11246
st_loggerr2        11247


(34030, 57)

In [182]:
df3.head(2)

pl_name hostname  default_flag  sy_snum  sy_pnum  pl_controv_flag  \
0  11 Com b   11 Com             1        2        1                0   
1  11 Com b   11 Com             0        2        1                0   

   pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  ...  sy_disterr2  \
0     326.03           0.32          -0.32           0.0  ...      -1.9238   
1        NaN            NaN            NaN           NaN  ...      -1.9238   

   sy_vmag  sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  \
0  4.72307        0.023       -0.023    2.282        0.346       -0.346   
1  4.72307        0.023       -0.023    2.282        0.346       -0.346   

   sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2  
0     4.44038        0.003848       -0.003848  
1     4.44038        0.003848       -0.003848  

[2 rows x 57 columns]

In [183]:
#欠損値が１個のところは切り捨てる
df4 = df3.dropna(subset=['default_flag', 'sy_snum', 'sy_pnum', 'pl_controv_flag', 'ttv_flag', 'rastr', 'ra', 'decstr', 'dec'])
print(df4.shape)
df4.isnull().sum()

(34030, 57)


pl_name                0
hostname               0
default_flag           0
sy_snum                0
sy_pnum                0
pl_controv_flag        0
pl_orbper           2979
pl_orbpererr1       4236
pl_orbpererr2       4237
pl_orbperlim        2979
pl_orbsmax         15360
pl_orbsmaxlim      12654
pl_rade            10566
pl_radeerr1        11217
pl_radeerr2        11217
pl_radelim          7894
pl_orbeccenlim     14387
pl_insollim        14672
pl_eqtlim          15879
ttv_flag               0
st_teff             2518
st_tefferr1         3208
st_tefferr2         3449
st_tefflim          2518
st_rad              2402
st_raderr1          7825
st_raderr2          7964
st_radlim           2402
st_mass             5326
st_masserr1        10645
st_masserr2        10784
st_masslim          5326
st_met             12653
st_meterr1         13307
st_meterr2         13307
st_metlim          10381
st_metratio        12842
st_logg             6093
st_loggerr1        11246
st_loggerr2        11247


In [184]:
df4.to_csv('/content/pl_data.csv')

In [185]:
"""st_metratio_d = pd.get_dummies(df4['st_metratio'], drop_first=True)
df5 = pd.concat([df4, st_metratio_d], axis=1)
df5 = df5.drop('st_metratio', axis=1)"""

"st_metratio_d = pd.get_dummies(df4['st_metratio'], drop_first=True)\ndf5 = pd.concat([df4, st_metratio_d], axis=1)\ndf5 = df5.drop('st_metratio', axis=1)"

In [186]:
#検出率が下がってしまったので今回はst_metratio列は切り捨てる
df5 = df4.drop(columns='st_metratio')

In [187]:
rastr_d = pd.to_datetime(df5['rastr'],  format='%Hh%Mm%S.%fs')
rastr_d

0       1900-01-01 12:20:42.910
1       1900-01-01 12:20:42.910
2       1900-01-01 15:17:05.900
3       1900-01-01 15:17:05.900
4       1900-01-01 15:17:05.900
                  ...          
34025   1900-01-01 01:36:47.600
34026   1900-01-01 01:36:47.600
34027   1900-01-01 11:36:56.930
34028   1900-01-01 19:54:14.990
34029   1900-01-01 19:54:14.990
Name: rastr, Length: 34030, dtype: datetime64[ns]

In [188]:
df5 = pd.concat([df5, rastr_d], axis=1)
df5 = df5.drop('rastr', axis=1)

In [189]:
#decstr_d = pd.to_datetime(df5['decstr'],  format='+%yd%Mm%S.%fs'or'-%yd%Mm%S.%fs')
#decstr_d

'''try:
  decstr_d = pd.to_datetime(df5['decstr'],  format='+%yd%Mm%S.%fs')
except ValueError:
  decstr_d = pd.to_datetime(df5['decstr'],  format='-%yd%Mm%S.%fs')'''

'''decstr_c = []
count = 0

for i in range(34030):
  try:
    decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='+%yd%Mm%S.%fs'))
  except ValueError:
    try:
      decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='-%yd%Mm%S.%fs'))
    except ValueError:
      decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='-%yd%Mm%Ss'))

decstr_d = pd.Series(decstr_c)'''

"decstr_c = []\ncount = 0\n\nfor i in range(34030):\n  try:\n    decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='+%yd%Mm%S.%fs'))\n  except ValueError:\n    try:\n      decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='-%yd%Mm%S.%fs'))\n    except ValueError:\n      decstr_c.append(pd.to_datetime(df5.loc[i,'decstr'],  format='-%yd%Mm%Ss'))\n\ndecstr_d = pd.Series(decstr_c)"

In [190]:
#decstr_d

In [191]:
# COLUMN decstr:         Dec [sexagesimal]
#60進法による惑星系の赤緯

In [192]:
#decstrの変換が上手くいかないため今回は捨てる
df5 = df5.drop('decstr', axis=1)

In [193]:
df5.isnull().sum()

pl_name                0
hostname               0
default_flag           0
sy_snum                0
sy_pnum                0
pl_controv_flag        0
pl_orbper           2979
pl_orbpererr1       4236
pl_orbpererr2       4237
pl_orbperlim        2979
pl_orbsmax         15360
pl_orbsmaxlim      12654
pl_rade            10566
pl_radeerr1        11217
pl_radeerr2        11217
pl_radelim          7894
pl_orbeccenlim     14387
pl_insollim        14672
pl_eqtlim          15879
ttv_flag               0
st_teff             2518
st_tefferr1         3208
st_tefferr2         3449
st_tefflim          2518
st_rad              2402
st_raderr1          7825
st_raderr2          7964
st_radlim           2402
st_mass             5326
st_masserr1        10645
st_masserr2        10784
st_masslim          5326
st_met             12653
st_meterr1         13307
st_meterr2         13307
st_metlim          10381
st_logg             6093
st_loggerr1        11246
st_loggerr2        11247
st_logglim          6093


In [194]:
'''non_df = df5.dropna()
from sklearn.linear_model import LinearRegression
x = non_df.loc[:, 'default_flag':'sy_gaiamagerr1']
t = non_df['sy_gaiamagerr2']
model = LinearRegression()
model.fit(x,t)'''

"non_df = df5.dropna()\nfrom sklearn.linear_model import LinearRegression\nx = non_df.loc[:, 'default_flag':'sy_gaiamagerr1']\nt = non_df['sy_gaiamagerr2']\nmodel = LinearRegression()\nmodel.fit(x,t)"

In [195]:
'''condition = df5['sy_gaiamagerr2'].isnull()
non_data = df5.loc[condition]
print(non_data)

x = non_data.loc[:, 'default_flag':'sy_gaiamagerr1']
pred = model.predict(x)

df5.loc[condition, 'sy_gaiamagerr2'] = pred'''

"condition = df5['sy_gaiamagerr2'].isnull()\nnon_data = df5.loc[condition]\nprint(non_data)\n\nx = non_data.loc[:, 'default_flag':'sy_gaiamagerr1']\npred = model.predict(x)\n\ndf5.loc[condition, 'sy_gaiamagerr2'] = pred"

In [196]:
df6 = df5.fillna(df5.mean())

<ipython-input-196-63dd55d4ec37>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df6 = df5.fillna(df5.mean())


In [197]:
live_li = []
live = pd.Series(live_li,name="live")
df7 = pd.concat([df6,live],axis=1)
df7.head(2)

<ipython-input-197-e5cb994867e2>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  live = pd.Series(live_li,name="live")


pl_name hostname  default_flag  sy_snum  sy_pnum  pl_controv_flag  \
0  11 Com b   11 Com             1        2        1                0   
1  11 Com b   11 Com             0        2        1                0   

      pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  ...  sy_vmag  \
0    326.030000       0.320000      -0.320000      0.000000  ...  4.72307   
1  13663.084629   15968.462645   -3538.776129     -0.000225  ...  4.72307   

   sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  sy_gaiamag  \
0        0.023       -0.023    2.282        0.346       -0.346     4.44038   
1        0.023       -0.023    2.282        0.346       -0.346     4.44038   

   sy_gaiamagerr1  sy_gaiamagerr2  live  
0        0.003848       -0.003848   NaN  
1        0.003848       -0.003848   NaN  

[2 rows x 55 columns]

In [198]:
df7 = df7.fillna(0)
df7.head(2)

pl_name hostname  default_flag  sy_snum  sy_pnum  pl_controv_flag  \
0  11 Com b   11 Com             1        2        1                0   
1  11 Com b   11 Com             0        2        1                0   

      pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  ...  sy_vmag  \
0    326.030000       0.320000      -0.320000      0.000000  ...  4.72307   
1  13663.084629   15968.462645   -3538.776129     -0.000225  ...  4.72307   

   sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  sy_gaiamag  \
0        0.023       -0.023    2.282        0.346       -0.346     4.44038   
1        0.023       -0.023    2.282        0.346       -0.346     4.44038   

   sy_gaiamagerr1  sy_gaiamagerr2  live  
0        0.003848       -0.003848   0.0  
1        0.003848       -0.003848   0.0  

[2 rows x 55 columns]

In [199]:
df7.loc[(df7['pl_name'] == "Teegarden's Star b"), 'live'] = 1
df7.loc[(df7['pl_name'] == "TOI-700 d"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-1649 c"), 'live'] = 1
df7.loc[(df7['pl_name'] == "TRAPPIST-1 d"), 'live'] = 1
df7.loc[(df7['pl_name'] == "GJ 1061 d"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Proxima Cen b"), 'live'] = 1
df7.loc[(df7['pl_name'] == "K2-72 e"), 'live'] = 1
df7.loc[(df7['pl_name'] == "GJ 1061 c"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Ross 128 b"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-296 e"), 'live'] = 1
df7.loc[(df7['pl_name'] == "TRAPPIST-1 e"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-442 b"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-62 f"), 'live'] = 1
df7.loc[(df7['pl_name'] == "TRAPPIST-1 f"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Teegarden's Star c"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-1229 b"), 'live'] = 1
df7.loc[(df7['pl_name'] == "Kepler-186 f"), 'live'] = 1
df7.loc[(df7['pl_name'] == "TRAPPIST-1 g"), 'live'] = 1
df7.loc[(df7['pl_name'] == "GJ 3293 d"), 'live'] = 2
df7.loc[(df7['pl_name'] == "HD 40307 g"), 'live'] = 2
df7.loc[(df7['pl_name'] == "HD 216520 c"), 'live'] = 2
df7.loc[(df7['pl_name'] == "HIP 38594 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "K2-9 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "K2-18 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "K2-288 B b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "K2-332 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "LHS 1140 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "TOI-2257 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Wolf 1061 c"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-22 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-62 e"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-155 c"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-174 d"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-283 c"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-296 f"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-440 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-443 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-452 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-705 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1410 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1540 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1544 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1606 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1638 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1652 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1653 b"), 'live'] = 2
df7.loc[(df7['pl_name'] == "Kepler-1701 b"), 'live'] = 2

In [200]:
#ここからモデルの作成
#ランダムフォレスト

In [201]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [202]:
# 訓練データ、検証データ、テストデータに分割

In [203]:
x = df7.loc[:,'default_flag':'sy_gaiamagerr2']
t = df7['live']

x_train, x_test, y_train, y_test = train_test_split(x, t, test_size = 0.2, random_state=0)
x_training, x_val, y_training, y_val = train_test_split(x, t, test_size = 0.2, random_state=0)

model = RandomForestClassifier(n_estimators=100, random_state=0)
model.fit(x_training, y_training)
model.score(x_val, y_val)

0.9975022039377021

In [204]:
#超不均衡データのため正解率が高くなってしまっているため、今回は基準を検出率に変える

In [205]:
import numpy as np

In [206]:
# 検証データから予測されたデータ
y_pred = model.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
print(u)
print(counts)

[0. 1. 2.]
[6774   11   21]


In [207]:
# 正解データ
u, counts = np.unique(y_val, return_counts=True)
print(u)
print(counts)

[0. 1. 2.]
[6757   13   36]


In [208]:
y_pred = model.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
u2, counts_2 = np.unique(y_val, return_counts=True)
print('1の検出率:', counts[1]/counts_2[1])
print('2の検出率:', counts[2]/counts_2[2])
print()

1の検出率: 0.8461538461538461
2の検出率: 0.5833333333333334



In [209]:
# 検出率が低いため目標値以下のためここからいろいろ試す
# 不均衡データのためランダムフォレストモデルに　class_weight='balanced'　を追加してみる

In [210]:
model2 = RandomForestClassifier(n_estimators=100, random_state=0, class_weight='balanced')
model2.fit(x_training, y_training)
model2.score(x_val, y_val)

0.9969144872171614

In [211]:
y_pred = model2.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
print(u)
print(counts)

[0. 1. 2.]
[6778    9   19]


In [212]:
u, counts = np.unique(y_val, return_counts=True)
print(u)
print(counts)

[0. 1. 2.]
[6757   13   36]


In [213]:
y_pred = model2.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
u2, counts_2 = np.unique(y_val, return_counts=True)
print('1の検出率:', counts[1]/counts_2[1])
print('2の検出率:', counts[2]/counts_2[2])
print()

1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778



In [214]:
# 1の検出率: 0.8461538461538461
# 2の検出率: 0.5833333333333334
# 上記は前回の検出率
# 検出率が下がっているのでclass_weight='balanced'はない方がよさそう

In [215]:
# ランダムフォレストの木の数の変更
model2 = RandomForestClassifier(n_estimators=50, random_state=0)
model2.fit(x_training, y_training)
model2.score(x_val, y_val)

y_pred = model2.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
print(u)
print(counts)

u, counts = np.unique(y_val, return_counts=True)
print(u)
print(counts)

[0. 1. 2.]
[6773   12   21]
[0. 1. 2.]
[6757   13   36]


In [216]:
# for文を使って木の最適な数を探索
for i in range(10, 101, 10):
  model2 = RandomForestClassifier(n_estimators=i, random_state=0)
  model2.fit(x_training, y_training)
  model2.score(x_val, y_val)

  y_pred = model2.predict(x_val)
  u, counts = np.unique(y_pred, return_counts=True)
  u2, counts_2 = np.unique(y_val, return_counts=True)
  print('深さ:',i)
  print('1の検出率:', counts[1]/counts_2[1])
  print('2の検出率:', counts[2]/counts_2[2])
  print()

深さ: 10
1の検出率: 0.7692307692307693
2の検出率: 0.4444444444444444

深さ: 20
1の検出率: 0.8461538461538461
2の検出率: 0.5

深さ: 30
1の検出率: 0.7692307692307693
2の検出率: 0.5277777777777778

深さ: 40
1の検出率: 0.9230769230769231
2の検出率: 0.5277777777777778

深さ: 50
1の検出率: 0.9230769230769231
2の検出率: 0.5833333333333334

深さ: 60
1の検出率: 0.9230769230769231
2の検出率: 0.5833333333333334

深さ: 70
1の検出率: 0.8461538461538461
2の検出率: 0.5833333333333334

深さ: 80
1の検出率: 0.9230769230769231
2の検出率: 0.5833333333333334

深さ: 90
1の検出率: 0.9230769230769231
2の検出率: 0.5833333333333334

深さ: 100
1の検出率: 0.8461538461538461
2の検出率: 0.5833333333333334



In [217]:
# 木の数が50以降は2の検出率が変わらない
# 深さ80,90が最も検出率が高い

In [218]:
# 念のため class_weight='balanced' を追加して検証してみる
for i in range(10, 101, 10):
  model2 = RandomForestClassifier(n_estimators=i, random_state=0, class_weight='balanced')
  model2.fit(x_training, y_training)
  model2.score(x_val, y_val)

  y_pred = model2.predict(x_val)
  u, counts = np.unique(y_pred, return_counts=True)
  u2, counts_2 = np.unique(y_val, return_counts=True)
  print('深さ:',i)
  print('1の検出率:', counts[1]/counts_2[1])
  print('2の検出率:', counts[2]/counts_2[2])
  print()

深さ: 10
1の検出率: 0.6153846153846154
2の検出率: 0.5

深さ: 20
1の検出率: 0.5384615384615384
2の検出率: 0.5555555555555556

深さ: 30
1の検出率: 0.5384615384615384
2の検出率: 0.6111111111111112

深さ: 40
1の検出率: 0.6153846153846154
2の検出率: 0.5277777777777778

深さ: 50
1の検出率: 0.6153846153846154
2の検出率: 0.5277777777777778

深さ: 60
1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778

深さ: 70
1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778

深さ: 80
1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778

深さ: 90
1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778

深さ: 100
1の検出率: 0.6923076923076923
2の検出率: 0.5277777777777778



In [219]:
#木の数を変えてもclass_weight='balanced'は検出率が低い

In [220]:
# 2の検出率を上げるためにアダブーストを使用してみる
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

base = DecisionTreeRegressor(random_state=0,max_depth=10)

model3 = AdaBoostRegressor(random_state=0, n_estimators=100, estimator=base)
model3.fit(x_training, y_training)
model3.score(x_val, y_val)

0.7966543216683537

In [221]:
# スコアが役80%…
# ランダムフォレストに比べて下がった…

In [222]:
y_pred = model3.predict(x_val)
u, counts = np.unique(y_pred, return_counts=True)
u2, counts_2 = np.unique(y_val, return_counts=True)
print('深さ:',i)
print('1の検出率:', counts[1]/counts_2[1])
print('2の検出率:', counts[2]/counts_2[2])
print()

深さ: 100
1の検出率: 0.23076923076923078
2の検出率: 0.027777777777777776



In [223]:
# 検出率も低いためランダムフォレストに比べてよいモデルではない

In [224]:
# 木の深さと木の数を二重ループで探索
"""for i in range(1,51,5):
  print('木の深さ',i,'-------------------------------------------------')
  for j in range(10, 101, 10):
    base = DecisionTreeRegressor(random_state=0,max_depth=i)
    model3 = AdaBoostRegressor(random_state=0, n_estimators=j, estimator=base)
    model3.fit(x_training, y_training)
    model3.score(x_val, y_val)
    y_pred = model3.predict(x_val)
    u, counts = np.unique(y_pred, return_counts=True)
    u2, counts_2 = np.unique(y_val, return_counts=True)
    print('深さ:',j)
    print('1の検出率:', counts[1]/counts_2[1])
    try:
      print('2の検出率:', counts[2]/counts_2[2])
    except IndexError:
      pass
    print()"""

"for i in range(1,51,5):\n  print('木の深さ',i,'-------------------------------------------------')\n  for j in range(10, 101, 10):\n    base = DecisionTreeRegressor(random_state=0,max_depth=i)\n    model3 = AdaBoostRegressor(random_state=0, n_estimators=j, estimator=base)\n    model3.fit(x_training, y_training)\n    model3.score(x_val, y_val)\n    y_pred = model3.predict(x_val)\n    u, counts = np.unique(y_pred, return_counts=True)\n    u2, counts_2 = np.unique(y_val, return_counts=True)\n    print('深さ:',j)\n    print('1の検出率:', counts[1]/counts_2[1])\n    try:\n      print('2の検出率:', counts[2]/counts_2[2])\n    except IndexError:\n      pass\n    print()"

In [225]:
# 処理が重いため断念…
# アダブーストはなし

In [226]:
# ロジスティック回帰で検証
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
new_train = sc.fit_transform(x_training)
new_val = sc.fit_transform(x_val)

In [227]:
from sklearn.linear_model import LogisticRegression
model4 = LogisticRegression(random_state=0, C = 0.1, multi_class='auto', solver ='lbfgs')
model4.fit(new_train,y_training)
model4.score(new_val,y_val)

0.9929473993535116

In [228]:
# スコアは高い

In [229]:
y_pred = model4.predict(new_val)
u, counts = np.unique(y_pred, return_counts=True)
u2, counts_2 = np.unique(y_val, return_counts=True)
print('1の検出率:', counts[1]/counts_2[1])
print('2の検出率:', counts[2]/counts_2[2])

1の検出率: 0.3076923076923077
2の検出率: 0.027777777777777776


In [230]:
# 低い...........
# 検出率がかなり低いためこのモデルは使い物にならない…

In [231]:
# 今回検証した中で最適だったのはランダムフォレストだったので改めて作成
last_model = RandomForestClassifier(n_estimators=80, random_state=0)
last_model.fit(x_training, y_training)
last_model.score(x_test, y_test)

y_pred = last_model.predict(x_test)
u, counts = np.unique(y_pred, return_counts=True)
print(u)
print(counts)
u_2, counts_2 = np.unique(y_test, return_counts=True)
print(u_2)
print(counts_2)
print('1の検出率:', counts[1]/counts_2[1])
print('2の検出率:', counts[2]/counts_2[2])

[0. 1. 2.]
[6773   12   21]
[0. 1. 2.]
[6757   13   36]
1の検出率: 0.9230769230769231
2の検出率: 0.5833333333333334


In [232]:
#ランダムフォレストの木の数80,90が一番高い
#しかし、2の再現率が58％のため改善の余地あり

In [235]:
from sklearn.metrics import classification_report
pred = last_model.predict(x_test)
out_put = classification_report(y_pred = pred, y_true = y_test)
print(out_put)

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      6757
         1.0       1.00      0.92      0.96        13
         2.0       1.00      0.58      0.74        36

    accuracy                           1.00      6806
   macro avg       1.00      0.84      0.90      6806
weighted avg       1.00      1.00      1.00      6806



In [249]:
pd.DataFrame(last_model.feature_importances_, index = x.columns)

0
default_flag     0.002070
sy_snum          0.001841
sy_pnum          0.012785
pl_controv_flag  0.019198
pl_orbper        0.102493
pl_orbpererr1    0.045674
pl_orbpererr2    0.047747
pl_orbperlim     0.004518
pl_orbsmax       0.030424
pl_orbsmaxlim    0.003253
pl_rade          0.031641
pl_radeerr1      0.020382
pl_radeerr2      0.024798
pl_radelim       0.002363
pl_orbeccenlim   0.004712
pl_insollim      0.000000
pl_eqtlim        0.002863
ttv_flag         0.002521
st_teff          0.036490
st_tefferr1      0.016432
st_tefferr2      0.014168
st_tefflim       0.000653
st_rad           0.028038
st_raderr1       0.008386
st_raderr2       0.006056
st_radlim        0.000909
st_mass          0.021193
st_masserr1      0.008254
st_masserr2      0.007682
st_masslim       0.000692
st_met           0.013195
st_meterr1       0.008344
st_meterr2       0.007758
st_metlim        0.002196
st_logg          0.018118
st_loggerr1      0.006721
st_loggerr2      0.008887
st_logglim       0.003108
ra               0.023601
dec              0.037547
sy_dist          0.035174
sy_disterr1      0.030201
sy_disterr2      0.028364
sy_vmag          0.037066
sy_vmagerr1      0.019620
sy_vmagerr2      0.026731
sy_kmag          0.031420
sy_kmagerr1      0.020480
sy_kmagerr2      0.023454
sy_gaiamag       0.033982
sy_gaiamagerr1   0.037790
sy_gaiamagerr2   0.038006